### PR TITLE
Added polybet's logo for the request and identified the request for polybet

### PR DESCRIPTION
**Pull request by pJJ3030**
Added PolyBet's logo for the request and identified the request for PolyBet. Created the select options needed based on the ancillary data. As we wanted functionality similar to PolyMarket, we copied code from them. However, I didn't want to use the same functions directly, as they might change their functionality later, which we might not be interested in.

### CODE REVIEW

**Comment by daywiss** [comment]
@pJJ3030 can you run `yarn lint-fix` to fix some of the formatting issues

**Comment by pJJ3030** [comment]
Fixed them, please review

**Comment by pJJ3030** [comment]
Fixed it, please review

**Review by daywiss — APPROVED** [review]
looks great, thanks for adding this

**Pull request merged**
